### PR TITLE
TH-48 Link component & typography extension

### PR DESCRIPTION
**Pull request by Onibenjo**

### CODE REVIEW

**Review by BrianJunk — COMMENTED** [review]
Can you explain to me how this works?

**Comment by Onibenjo** [comment]
This is a Link component used for places where hyper links are used. Eg. External links to mails or phone numbers etc.

**Comment by BrianJunk** [comment]
no I mean the typography mapping and overrides etc

**Comment by Onibenjo** [comment]
Oh okay, I have not added all the text styles to the theme yet
So I did that here due to the Link component
Our textstyles are different from mui's own since we use 2 fonts
So I had to add custom text styles and followed the naming convention on figma for consistency

**Review by BrianJunk — APPROVED** [review]

**Pull request merged**
